/**
 * FIFA/Coca-Cola Men's World Ranking tie-breaker (step 3).
 * Lower number = better. Update when FIFA publishes a new list.
 * Keys match OpenFootball team names in our DB.
 */
export const FIFA_RANK_BY_TEAM_NAME: Record<string, number> = {
  Argentina: 1,
  France: 2,
  Spain: 3,
  England: 4,
  Brazil: 5,
  Portugal: 6,
  Netherlands: 7,
  Belgium: 8,
  Germany: 9,
  Croatia: 10,
  Morocco: 11,
  Colombia: 12,
  Uruguay: 13,
  Mexico: 14,
  "United States": 15,
  USA: 15,
  Switzerland: 16,
  Japan: 17,
  Senegal: 18,
  Iran: 19,
  "South Korea": 20,
  Ecuador: 21,
  Austria: 22,
  Australia: 23,
  Norway: 24,
  Panama: 25,
  Egypt: 26,
  Algeria: 27,
  "Côte d'Ivoire": 28,
  "Ivory Coast": 28,
  Scotland: 29,
  Paraguay: 30,
  Tunisia: 31,
  "Cape Verde": 32,
  Sweden: 33,
  Poland: 34,
  Ukraine: 35,
  "Czech Republic": 36,
  Czechia: 36,
  Denmark: 37,
  Serbia: 38,
  Wales: 39,
  Canada: 40,
  Qatar: 41,
  Iraq: 42,
  "Saudi Arabia": 43,
  Jordan: 44,
  Uzbekistan: 45,
  Ghana: 46,
  "DR Congo": 47,
  Congo: 47,
  Haiti: 48,
  Curaçao: 49,
  Curacao: 49,
  "Bosnia & Herzegovina": 50,
  "Bosnia and Herzegovina": 50,
  "New Zealand": 55,
  "South Africa": 60,
  Turkey: 61,
  Türkiye: 61,
};

export function fifaRankForTeamName(name: string) {
  return FIFA_RANK_BY_TEAM_NAME[name] ?? 999;
}
